[package]
name = "flag-frenzy"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
toml = { version = "0.8.14", default-features = false, features = ["parse"] }
