[[rule]]
when = true
require = [
    "always-required",
    ["choose-required-1", "OR", "choose-required-2"],
]
forbid = "always-fails"

[[rule]]
when = ["incompatible-1", "incompatible-2"]
forbid = true
