[features]
required = [
    # `foo` will always be enabled.
    "foo",
    # Either `bar` or `baz` will always be enabled.
    ["bar", "baz"],
]

incompatible = [
    # `bar` cannot be compiled with `baz`.
    ["bar", "baz"],
]

skip = [
    # Never test `bev`.
    "bev",
]

max_combo_size = 4
