name: CI

on:
  # Runs every Sunday at midnight.
  schedule:
    - cron: 0 0 * * 0
  # Allow running manually.
  workflow_dispatch:

env:
  # Force colorful output, even though we're running in Github Actions.
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check chunk ${{ matrix.chunk }}
    runs-on: ubuntu-latest
    strategy:
      # One chunk failing should not cancel another.
      fail-fast: false
      matrix:
        chunk: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout Bevy
        uses: actions/checkout@v4
        with:
          repository: bevyengine/bevy
          path: bevy

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache build files
        uses: Leafwing-Studios/cargo-cache@v2
        with:
          # Each chunk saves to a separate cache.
          cache-group: ${{ github.job }}-${{ matrix.chunk }}
          cargo-target-dir: bevy/target

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          # Installs Alsa, udev, and Wayland.
          sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev

      - name: Build tool
        run: cargo build --release

      - name: Check all features
        run: cargo run --release -- --manifest-path bevy/Cargo.toml --config config --total-chunks 10 --chunk ${{ matrix.chunk }}
